name: '使用自创建action'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  output-time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: '测试'
        id: output-RanDomNum
        uses: lNEWBEEl/echorandomnum@v1
