name: '输出当前时间'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  output-time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: '输出一个随机数'
        id: output-RanDomNum
        uses: lNEWBEEl/echorandomnum@v1
