name: '输出当前时间'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  output-time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: npm install
        run: npm install

      - name: '输出当前时间'
        id: output-time
        uses: lNEWBEEl/echotime@v1.0.0
