name: '输出当前时间'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  output-time:
    runs-on: ubuntu-latest

    steps:
      - name: '输出当前时间'
        id: output-time
        uses: lNEWBEEl/echotime@main
